### ISSUE TITLE
Props becoming Perma props after map change/ server restart?

### ISSUE THREAD

**Issue by Metermann001** [TacoNBanana/Eternity-Issues#2]
**Describe the bug**

Tonight on the 5th July 2021 we map switched to C18_v2, after some discussing with the other admins we changed back to I17. There we ran into a problem where all of the players prop that were on the server at the time became perma props-

**To Reproduce**

(example)
1. type rpa_changelevel in console
2. Change to a different map after putting some no perma props down
3. Go back to the map you were on first
4. Tada, you can see that the prop is now perma even tho it was never made perma by a admin

**Expected behavior**
Pretty much any non perma props on server made by a player or admin become a perma prop, haven't tested it with restarts yet but I assume it could also happen then.

**Comment by Gangleider** [comment]
Temporary workaround is using the cleanup menu to clear all props before map change, but will look at this asap

**Comment by Gangleider** [comment]
This should be fixed.
